// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShiftTracker.Angular.Data;

#nullable disable

namespace ShiftTracker.Angular.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230124205625_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("EntityFrameworkHiLoSequence")
                .IncrementsBy(10);

            modelBuilder.Entity("ShiftTracker.Angular.Models.Break", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.ToTable("Breaks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Duration = new TimeSpan(0, 0, 30, 0, 0),
                            EndTime = new TimeSpan(0, 13, 0, 0, 0),
                            ShiftId = -1,
                            StartTime = new TimeSpan(0, 12, 30, 0, 0)
                        },
                        new
                        {
                            Id = -2,
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            ShiftId = -1,
                            StartTime = new TimeSpan(0, 15, 0, 0, 0)
                        },
                        new
                        {
                            Id = -3,
                            Duration = new TimeSpan(0, 1, 0, 0, 0),
                            EndTime = new TimeSpan(0, 10, 0, 0, 0),
                            ShiftId = -2,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = -4,
                            Duration = new TimeSpan(0, 0, 15, 0, 0),
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            ShiftId = -2,
                            StartTime = new TimeSpan(0, 13, 45, 0, 0)
                        });
                });

            modelBuilder.Entity("ShiftTracker.Angular.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "EntityFrameworkHiLoSequence");

                    b.Property<TimeSpan>("BreakDuration")
                        .HasColumnType("time");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("DriveTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("OtherWorkTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("ShiftDuration")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("WorkTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("Shifts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            BreakDuration = new TimeSpan(0, 1, 30, 0, 0),
                            Date = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriveTime = new TimeSpan(0, 2, 55, 0, 0),
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            OtherWorkTime = new TimeSpan(0, 2, 5, 0, 0),
                            ShiftDuration = new TimeSpan(0, 8, 0, 0, 0),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            WorkTime = new TimeSpan(0, 1, 30, 0, 0)
                        },
                        new
                        {
                            Id = -2,
                            BreakDuration = new TimeSpan(0, 0, 30, 0, 0),
                            Date = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriveTime = new TimeSpan(0, 2, 0, 0, 0),
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            OtherWorkTime = new TimeSpan(0, 2, 0, 0, 0),
                            ShiftDuration = new TimeSpan(0, 6, 0, 0, 0),
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            WorkTime = new TimeSpan(0, 1, 30, 0, 0)
                        });
                });

            modelBuilder.Entity("ShiftTracker.Angular.Models.Break", b =>
                {
                    b.HasOne("ShiftTracker.Angular.Models.Shift", "Shift")
                        .WithMany("Breaks")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("ShiftTracker.Angular.Models.Shift", b =>
                {
                    b.Navigation("Breaks");
                });
#pragma warning restore 612, 618
        }
    }
}
